# Generated by Django 6.0.6 on 2026-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва вакансії')),
                ('company', models.CharField(max_length=255, verbose_name='Компанія')),
                ('location', models.CharField(max_length=255, verbose_name='Місто / Локація')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Зарплата')),
                ('description', models.TextField(verbose_name='Опис вакансії')),
                ('source_url', models.URLField(blank=True, null=True, unique=True, verbose_name='Посилання на першоджерело')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Вакансія',
                'verbose_name_plural': 'Вакансії',
                'ordering': ['-created_at'],
            },
        ),
    ]
