# Generated by Django 6.0.6 on 2026-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(default='Не вказана', max_length=100, verbose_name='Зарплата'),
        ),
    ]
